name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff mypy bandit safety
    
    - name: Run ruff linting
      run: |
        ruff check . --output-format=github
    
    - name: Run ruff formatting check
      run: |
        ruff format --check . --diff
    
    - name: Type checking with mypy
      run: |
        mypy mcp_python_baremetal/ --ignore-missing-imports --no-strict-optional
      continue-on-error: true  # Type checking is advisory for now
    
    - name: Security check with bandit
      run: |
        bandit -r mcp_python_baremetal/ -f json -o bandit-report.json || true
        bandit -r mcp_python_baremetal/ -f txt
      continue-on-error: true  # Security check is advisory
    
    - name: Check dependencies for known security vulnerabilities
      run: |
        safety check --json --output safety-report.json || true
        safety check
      continue-on-error: true  # Dependency check is advisory
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
        retention-days: 7

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Test README examples
      run: |
        # Verify all CLI commands in README work
        mcp-python-baremetal --help
        mcp-python-baremetal serve --help
        mcp-python-baremetal http --help
        mcp-python-baremetal execute --help
        mcp-python-baremetal libraries
        mcp-python-baremetal demo --help
    
    - name: Validate package metadata
      run: |
        python -m pip install twine
        python -m build
        twine check dist/*